backend:
  name: git-gateway
  branch: main   # or master, depending on your repo’s default branch

media_folder: "uploads"     # uploaded files stored in /uploads
public_folder: "/uploads"

collections:
  - name: "portfolio"
    label: "Portfolio Files"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "File", name: "file", widget: "file" }

